# Generated by Django 3.2.18 on 2024-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.PositiveIntegerField(default=30000, verbose_name='Зарплата'),
        ),
    ]
