# Generated by Django 3.2.18 on 2024-02-10 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.IntegerField(default=1, help_text='Значение от 1 до 10', validators=[django.core.validators.MinValueValidator(1, 'Минимальное зачение-1'), django.core.validators.MaxValueValidator(10, 'Максимальное значение-10')], verbose_name='Важность навыка'),
        ),
    ]
